### ISSUE TITLE
Lage visittkort med koding "index.html"

### ISSUE THREAD

**Issue by ezizomer99** [3Beast/Gruppe-3B#2]
1. Skal inneholde 8 visittkort, 1 til hver gruppemedlem
2. Må kode inn informasjon til visittkort
3. Bruke CSS, html og JS

**Comment by ezizomer99** [comment]
Har lagt til visittkort Eziz Ømer

**Comment by EirikSNedland** [comment]
Lagt til visittkort eirik s nedland

**Comment by StianSteinsland** [comment]
Lagt til vissitkort Stian Steinsland

**Comment by Siljestrm** [comment]
Har lagt til visittkort Silje Elise Strøm

**Comment by lillesalt** [comment]
lagt til visittkort Frida L Valvik

**Comment by TonjeFM** [comment]
Lagt til visittkort Tonje F. Markseth

**Comment by helelou** [comment]
Lagt inn visittkort (i går), Helene Ludvigsen

**Comment by Asbjornhh** [comment]
Lagt inn visitkort, Asbjørn Håland Hestnes
